### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by cannaplanners** [BrianHenryIE/bh-wc-checkout-rate-limiter#9] opened 2021-12-15 17:03 UTC
Getting the following error when activating the latest version of the plugin:

`Parse error: syntax error, unexpected 'Logger_Settings_Interface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /Users/korymathis/Local Sites/healer/app/public/wp-content/plugins/bh-wc-checkout-rate-limiter/strauss/brianhenryie/wp-logger/src/Includes/class-bh-wp-logger.php on line 38`

**Comment by BrianHenryIE** [comment] 2022-01-14 05:45
Hey,

Sorry, I didn't notice this issue until now.

The problem is that this requires PHP 7.4, and that message appears when an earlier version of PHP doesn't understand the newer syntax. Updating PHP is the easiest, and best solution. I don't have any short-term plans to transpile this back to PHP 7.2 (which is WooCommerce's minimum requirement).

I've added the `* Requires PHP: 7.4` plugin header to the next version, which I think means WordPress will prevent it being installed on sites running older versions of PHP, so hopefully nobody else will have this problem.

**Comment by BrianHenryIE** [comment] 2022-10-16 03:57
[Fixed in v1.1.0](https://github.com/BrianHenryIE/bh-wc-checkout-rate-limiter/commit/87751c2a03e0c76c209ed90e9d0045ceddc86477).

**Closed by BrianHenryIE** 2022-10-16 03:57 UTC
